export enum ConfigEnum {
  PORT = 'PORT',
  DOMAIN = 'DOMAIN',
  WEB_DOMAIN = 'WEB_DOMAIN',

  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_CONNECTION_LIMIT = 'DATABASE_CONNECTION_LIMIT',

  JWT_SIGN_ALGORITHM = 'JWT_SIGN_ALGORITHM', // 'RS256' | 'HS256'
  JWT_EXPIRE = 'JWT_EXPIRE',
  JWT_REFRESH_EXPIRE = 'JWT_REFRESH_EXPIRE',
  JWT_PRIVATE_KEY = 'JWT_PRIVATE_KEY',

  HASH_SALT_ROUNDS = 'HASH_SALT_ROUNDS',

  ROOT_STORAGE_PATH = 'ROOT_STORAGE_PATH',
  ROOT_PUBLIC_STORAGE_PATH = 'ROOT_PUBLIC_STORAGE_PATH',
  IMAGES_PATH = 'IMAGES_PATH',
  PROFILE_PICTURES_IMAGES_PATH = 'PROFILE_PICTURES_IMAGES_PATH',
  POSTS_IMAGES_PATH = 'POSTS_IMAGES_PATH',

  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
  MAIL_FROM = 'MAIL_FROM',
}

export interface IConfig {
  PORT: number;
  DOMAIN: string;
  WEB_DOMAIN: string;

  DATABASE_HOST: string;
  DATABASE_PORT: number;
  DATABASE_USERNAME: string;
  DATABASE_PASSWORD: string;
  DATABASE_NAME: string;
  DATABASE_CONNECTION_LIMIT: number;

  JWT_SIGN_ALGORITHM: 'RS256' | 'HS256';
  JWT_EXPIRE: string | number;
  JWT_REFRESH_EXPIRE: string | number;
  JWT_PRIVATE_KEY: string;

  HASH_SALT_ROUNDS: number;

  ROOT_STORAGE_PATH: string;
  ROOT_PUBLIC_STORAGE_PATH: string;
  IMAGES_PATH: string;
  PROFILE_PICTURES_IMAGES_PATH: string;
  POSTS_IMAGES_PATH: string;

  SENDGRID_API_KEY: string;
  MAIL_FROM: string;
}
